name: Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_SERVER }} -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY_SERVER }}/si-project/backend:latest ./backend/
          docker push ${{ secrets.DOCKER_REGISTRY_SERVER }}/si-project/backend:latest

      - name: Deploy to Kubernetes
        run: |
          echo "$KUBECONFIG" > kubeconfig.yaml
          kubectl --kubeconfig=kubeconfig.yaml set image deployment/backend backend=${{ secrets.DOCKER_REGISTRY_SERVER }}/si-project/backend:latest -n my-namespace
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
